include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO bombomby/optick
    REF 1.2.9.0
    SHA512 9fb0b5c2207df6b61437ac6901ceaf768517438adf285b16c0035915d46eba720fa6052fda6e275318ee9b1782f7eea8ce3f7680603fda7ce2a001330a657a65
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DOPTICK_USE_VULKAN=${USE_VULKAN}
)

vcpkg_build_cmake(TARGET OptickCore)

file(INSTALL "${SOURCE_PATH}/src/optick.h" "${SOURCE_PATH}/src/optick.config.h" DESTINATION "${CURRENT_PACKAGES_DIR}/include/optick")

file (INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/OptickCore${VCPKG_TARGET_SHARED_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
file (INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/OptickCore${VCPKG_TARGET_SHARED_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
vcpkg_copy_pdbs()

file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/OptickCore${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/OptickCore${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/optick" RENAME copyright)
